name: microservicebus-node
version: '1.6' 
summary: ....
description: |
  microServiceBus.com ® enables businesses to combine the power of Enterprise Application Integration (EAI) with agility and reach of Internet of Things (IoT). https://microservicebus.com/
grade: devel 
confinement: devmode 

apps:
  microservicebus-node:
    command: bin/startsnap
    daemon: simple
    restart-condition: always
    plugs:
    - kernel-module-control
    - hardware-observe
    - serial-port
    - home
    - network
    - network-bind
    - modem-manager

environment:
  CPLUS_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu
  C_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu
  LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu
  PATH: $PATH:$SNAP/usr/bin
  PYTHON: $SNAP/usr/bin/python2.7
#    NODE_PATH: $NODE_PATH:/root/snap/microservicebus-node/x1/node_modules;/snap/microservicebus-node/x1/lib/node_modules;/snap/microservicebus-node/x1/lib/node_modules
#    PATH: $PATH:$SNAP/usr/bin
#    PYTHON: $SNAP/usr/bin/python2.7
#    CPLUS_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu
#    C_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu
#    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu
#    NODE_PATH: $NODE_PATH:$SNAP/lib/node_modules

#    NODE_DEBUG: module
#   $PATH: /snap/microservicebus-node/x1/usr/bin
#   PYTHON: /snap/microservicebus-node/x1/usr/bin/python2.7
#   CPLUS_INCLUDE_PATH: /snap/microservicebus-node/x1/usr/include

parts:
  node:
    source: https://github.com/axians/microservicebus-node.git
    source-branch: master
    plugin: nodejs
    node-engine: 7.10.0
    build-packages:
    - python2.7
    - build-essential
    stage-packages:
    - python2.7
    - build-essential
    node-packages: [serialport]
    stage:
      - -usr/lib/x86_64-linux-gnu/libc.so
      - -usr/lib/x86_64-linux-gnu/libm.so
      - -usr/lib/x86_64-linux-gnu/libpthread.so

  libhack:
    source: ./libhack
    plugin: dump


# sudo snap connect microservicebus-node:kernel-module-control core:kernel-module-control
# sudo snap connect microservicebus-node:hardware-observe core:hardware-observe
# sudo snap connect microservicebus-node:serial-port caracalla:ttys4

# sudo snap connect microservicebus-daemon:kernel-module-control core:kernel-module-control
# sudo snap connect microservicebus-daemon:hardware-observe core:hardware-observe
# sudo snap connect microservicebus-daemon:serial-port caracalla:ttys4
